### ISSUE TITLE
OAK-D Lite - Depthai 2.17.0.0 doesn't work on Windows as well as Ubuntu

### ISSUE THREAD

**Issue by rexn8r** [luxonis/depthai-experiments#377] opened 2022-07-14 13:11 UTC
I have OAK-D and OAK-D Lite both camera.

![image](https://user-images.githubusercontent.com/12812556/178992292-10e17e4e-a525-456a-99f1-21f67e3f572f.png)

**Windows OS**

Depthai 2.15 was already installed.

Ran following python commands to uninstall Version 2.15

python -m pip uninstall depthai -y

Ran following python command to install Version 2.17

python -m pip install depthai --no-cache-dir

Downloaded Gen2-Age-Gender demo files and executed main.py 

**Plugged OAK-D Lite Camera**

The program stuck and doesn't show capture window.

![image](https://user-images.githubusercontent.com/12812556/178987000-17f14c56-d125-44d4-b156-4da076d666b8.png)

**Ubuntu 22.04**

Similar problem found on Ubuntu 22.04 as well. It had V 2.15 and I upgraded to 2.17. Please refer my post on discussion board;

https://discuss.luxonis.com/d/766-3-stage-nn-not-working-with-multimsgsync-py/6

![image](https://user-images.githubusercontent.com/12812556/178987447-137a41f5-19df-4269-9944-7f9ab49fdc68.png)

**Plugged In OAK-D camera**

It started the capture and ran the demo;

![image](https://user-images.githubusercontent.com/12812556/178988386-2ba64f24-1fe9-4b5d-a392-97e3a6c9816d.png)

I modified the age/gender demo and removed the script node and used dai.NNData on the fly to do the inferencing and that is working fine on the Lite with 2.17
![image](https://user-images.githubusercontent.com/12812556/178991057-f134eb4d-6c68-436f-a65d-6e7f62ed9883.png)

So the problem on OAK-D Lite seem to be with the use of MultiMsgSync.py

Anyone facing similar issue?

thanks

**Comment by Erol444** [comment] 2022-07-14 14:43
Hi @rexn8r ,
Thanks for reporting! I can reproduce and I am debugging now.
Findings till now:
- if disabling stereo (add line `stereo=False` to line 144), it works

**Comment by Erol444** [comment] 2022-07-15 17:05
Hi @rexn8r , not yet, there seems to be some deeper issues (so firmware), I assume due to different stereo resolution. So I am still debugging this.

**Comment by szabi-luxonis** [comment] 2022-07-15 18:16
Might be related to [this](https://github.com/luxonis/depthai-experiments/issues/326#issuecomment-1126110431) one

**Comment by rexn8r** [comment] 2022-07-16 05:18
Hi @szabi-luxonis 

downloaded script from the same [link](https://gist.github.com/szabi-luxonis/a406aa5290bf2961b8f2e58485fe3f0f)
![szabi](https://user-images.githubusercontent.com/12812556/179338560-c9b48bc7-8df7-44e5-b43f-4762d7a46fe6.png)

It get stuck with 2.17.0.0 on Ubuntu 22.04 as well as Windows.

I uninstall 2.17.0.0 and used the following PR which you provided me in this [link](https://github.com/luxonis/depthai-experiments/issues/326#issuecomment-1124301011) 

python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.15.4.0.dev+7ce594fa6a2b8437be7fef010a26b1eb5eb1fdf8"

Now the Lite doesn't get stuck. I extended the script to include following emotion NN manip into the script node code but all the inferences are wrong as you can see in the below screenshot;

for i, det in enumerate(face_dets.detections):
                    correct_bb(det)
                    rr = RotatedRect()
                    rr.center.x = (det.xmin + det.xmax) / 2
                    rr.center.y = (det.ymin + det.ymax) / 2
                    rr.size.width = det.xmax - det.xmin
                    rr.size.height = det.ymax - det.ymin
                    rr.angle = -90
                    
                    #Age and Gender Manip
                    cfg = ImageManipConfig()
                    cfg.setCropRotatedRect(rr, True)
                    cfg.setResize(62, 62)
                    cfg.setKeepAspectRatio(False)
                    node.io['manip_cfg'].send(cfg)
                    node.io['manip_img'].send(img)
                    
                    #Expression Manip
                    **cfg2 = ImageManipConfig()
                    cfg2.setCropRotatedRect(rr, True)
                    cfg2.setResize(64, 64)
                    cfg2.setKeepAspectRatio(False)
                    node.io['emanip_cfg'].send(cfg2)
                    node.io['emanip_img'].send(img)**

![2 15](https://user-images.githubusercontent.com/12812556/179339312-c15196fa-15da-4140-ba01-5982e88d0b15.png)

Then I changed the  script node as follows;

**Removed rotation from the script node;**

for i, det in enumerate(face_dets.detections):
                    correct_bb(det)
                    **#rr = RotatedRect()
                    #rr.center.x = (det.xmin + det.xmax) / 2
                    #rr.center.y = (det.ymin + det.ymax) / 2
                    #rr.size.width = det.xmax - det.xmin
                    #rr.size.height = det.ymax - det.ymin
                    #rr.angle = -90**
                    
                    #Age and Gender Manip
                    cfg = ImageManipConfig()
                    #cfg.setCropRotatedRect(rr, True)
                    **cfg.setCropRect(det.xmin, det.ymin, det.xmax, det.ymax)**
                    cfg.setResize(62, 62)
                    cfg.setKeepAspectRatio(False)
                    node.io['manip_cfg'].send(cfg)
                    node.io['manip_img'].send(img)
                    
                    #Expression Manip
                    cfg2 = ImageManipConfig()
                    #cfg2.setCropRotatedRect(rr, True)
                    **cfg2.setCropRect(det.xmin, det.ymin, det.xmax, det.ymax)**
                    cfg2.setResize(64, 64)
                    cfg2.setKeepAspectRatio(False)
                    node.io['emanip_cfg'].send(cfg2)
                    node.io['emanip_img'].send(img)

Then instead of **cam.preview.link(image_manip_script.inputs['preview'])** passed face_det_manip to the preview as **face_det_manip.out.link(image_manip_script.inputs['preview'])**

The following screeshot shows ImageManip errors in between;

![Screenshot from 2022-07-16 10-03-32](https://user-images.githubusercontent.com/12812556/179339686-98728b91-bf64-4b87-8e14-e3b8ea5fc08b.png)

So my observations after fiddling with various scripts and sdk versions;

1. The PR which you have provided for -90 degree rotation as above doesn't seem to be part of 2.17.0.0
2. Irrespective of the SDK version, the script node with ImageManip -90 degree rotation along with **cam.preview.link(image_manip_script.inputs['preview'])** always return wrong inference because the preview is not rotated and the script node rotation cfg.setCropRotatedRect(rr, True) doesn't seem to work. If face_det_manip.out.link(image_manip_script.inputs['preview']) is used (face_det_manip is already rotated) with cfg.setCropRect(det.xmin, det.ymin, det.xmax, det.ymax) in the script node then the inference seem to return OK results but getting ImageManip errors in between.
3. If i don't use Script Node with MultiMsgSync.py and use dia.NNData as below on the fly as a work around, everything is working fine Irrespective of the SDK version;

age_data = dai.NNData()
                age_data.setLayer("data", to_planar(det_frame, (62, 62)))
                agegender_in.send(age_data)
                age_det = agegender_nn.get()
                age = int(float(np.squeeze(np.array(age_det.getLayerFp16('age_conv3')))) * 100)
                gender = np.squeeze(np.array(age_det.getLayerFp16('prob')))
                gender_str = "female" if gender[0] > gender[1] else "male"

                exp_data = dai.NNData()
                exp_data.setLayer("data", to_planar(det_frame, (64, 64)))
                expression_in.send(exp_data)
                expression_data = expression_nn.get()
                exp_results = np.array(expression_data.getFirstLayerFp16())
                expression_str = class_names[np.argmax(exp_results)]

4. The Script node with MultiMsgSync.py seem to be quicker (20 FPS) then dai.NNData methods (15 FPS).

I have a client waiting for the solution to roll out customized display hardware with AI camera so request to suggest way forward which option to use as I am running out of time with testing OAK-D camera.

thanks

**Comment by szabi-luxonis** [comment] 2022-07-16 11:19
@rexn8r thanks for the data points. I understand the need here and we are triaging what could be the error.
Will get back to you once we have new findings.

**Comment by Erol444** [comment] 2022-07-16 14:40
@rexn8r  Addressed in [PR here](https://github.com/luxonis/depthai-experiments/pull/379). Thanks again for your testing!

**Closed** 2022-07-17 09:26 UTC

**Comment by rexn8r** [comment] 2022-07-17 11:37
Hi @Erol444 

Downloaded latest Age & Gender demo files. Added -90 Degree Rotation code but there is no detection;

when you get a chance, please check following script;

https://pastebin.com/HHZZtvrS

thanks
rex

**Comment by rexn8r** [comment] 2022-07-19 07:41
> Hi @Erol444
> 
> Downloaded latest Age & Gender demo files. Added -90 Degree Rotation code but there is no detection;
> 
> when you get a chance, please check following script;
> 
> https://pastebin.com/HHZZtvrS
> 
> thanks rex

hi @Erol444 

did u get a chance to look at this pastebin code?

thanks
rex

**Comment by Erol444** [comment] 2022-07-19 12:21
Hi @rexn8r ,
Not yet, I plan to address this after we get initial version of SDK released (to add support for rotated camera). 
WRT `Added -90 Degree Rotation code but there is no detection;` - if you are running inferences on rotated frames, model might not be trained on rotated frames, so there are no detections. Thoughts?
Thanks, Erik

**Comment by rexn8r** [comment] 2022-07-20 04:58
here's what i have done with main.py of age and gender demo for -90 degree rotation.

https://pastebin.com/VtxXyGdJ

the Z value coming out wrong. If face is moved extreme left or right, the values are different and I can't figure out how to solve it.

What's the ETA of sdk with support for rotation?

thanks

**Comment by szabi-luxonis** [comment] 2022-07-20 06:46
@rexn8r you need to use the library that I provided to you previously, not the latest release. It's a custom special branch.
