### ISSUE TITLE
Crash - segmentation fault

### ISSUE THREAD

**Issue by RudyAramayo** [luxonis/depthai-experiments#241] opened 2021-11-03 01:34 UTC
I got new requirements installed and the app crashes as soon as it recognizes me. It does present a window and shows camera with unknown. Running MacOSX Monterey 12.0 Beta (21A5506j)

zsh: segmentation fault  python3 main.py --name Rudy
Rodolfo@RIP gen2-face-recognition % python3 main.py --name Rudy
Creating pipeline...
Creating Color Camera...
Creating Face Detection Neural Network...
Creating Head pose estimation NN
Creating face recognition ImageManip/NN
[14442C10210D60D700] [11.883] [NeuralNetwork(10)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C10210D60D700] [12.127] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Traceback (most recent call last):
  File "main.py", line 254, in <module>
    frameIn = frameQ.tryGet()
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'frame' (X_LINK_ERROR)'
Rodolfo@RIP gen2-face-recognition % python3 main.py --name Rudy
Creating pipeline...
Creating Color Camera...
Creating Face Detection Neural Network...
Creating Head pose estimation NN
Creating face recognition ImageManip/NN
[14442C10210D60D700] [8.005] [NeuralNetwork(10)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C10210D60D700] [8.248] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Saving face...
Saving face...
Saving face...
Saving face...
zsh: segmentation fault  python3 main.py --name Rudy
Rodolfo@RIP gen2-face-recognition % python3 main.py --name Rudy
Creating pipeline...
Creating Color Camera...
Creating Face Detection Neural Network...
Creating Head pose estimation NN
Creating face recognition ImageManip/NN
[14442C10210D60D700] [20.261] [NeuralNetwork(10)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C10210D60D700] [20.504] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Stack trace (most recent call last) in thread 123145526829056:
#7    Object "libsystem_pthread.dylib", at 0x7ff80dd195a8, in _pthread_start + 125
#6    Object "depthai.cpython-38-darwin.so", at 0x11af6a617, in void fmt::v7::detail::value<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >::format_custom_arg<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, fmt::v7::formatter<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, char, void> >(void const*, fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>&, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>&) + 89687
#5    Object "libc++abi.dylib", at 0x7ff80dcdde84, in __cxa_decrement_exception_refcount + 35
#4    Object "libc++abi.dylib", at 0x7ff80dcdbd16, in std::runtime_error::~runtime_error() + 94
#3    Object "libc++abi.dylib", at 0x7ff80dcdec93, in __cxa_guard_acquire + 115
#2    Object "libsystem_platform.dylib", at 0x7ff80dd2f06c, in _sigtramp + 28
#1    Object "depthai.cpython-38-darwin.so", at 0x11b0076ed, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 13
#0    Object "depthai.cpython-38-darwin.so", at 0x11b00775c, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 124
zsh: segmentation fault  python3 main.py --name Rudy
Rodolfo@RIP gen2-face-recognition % python3 main.py --name Rudy
Creating pipeline...
Creating Color Camera...
Creating Face Detection Neural Network...
Creating Head pose estimation NN
Creating face recognition ImageManip/NN
[14442C10210D60D700] [8.429] [NeuralNetwork(10)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C10210D60D700] [8.672] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Saving face...
Saving face...
Saving face...
Saving face...
Saving face...
Traceback (most recent call last):
  File "main.py", line 254, in <module>
    frameIn = frameQ.tryGet()
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'frame' (X_LINK_ERROR)'
Rodolfo@RIP gen2-face-recognition % pwd
/Users/Rodolfo/Downloads/depthai-experiments-master/gen2-face-recognition
Rodolfo@RIP gen2-face-recognition %

**Comment by Luxonis-Brandon** [comment] 2021-11-03 05:01
Hi @RudyAramayo ,

Sorry about the trouble here.  We should have put this as a known issue.  We have been debugging a tricky underlying bug that seems to be the root cause of this.  It seems that we just today nailed it - I think - and if so, @themarpe I think has the details and also instructions on how to test the fix.  

Sorry again about the trouble here.

-Brandon

**Comment by RudyAramayo** [comment] 2021-11-03 13:26
I love you product, im so excited to use it on my droid. I preordered the lite version.. (2 pack). Even better is that you are absolutely on top of these with quick response, thank you. I can't wait to perform my camera calibration and continue testing further. C++ integration should be a blast!

**Comment by RudyAramayo** [comment] 2021-11-03 13:27
Can you believe the day that droids can recognize our entities and name them.. so exciting!

**Comment by themarpe** [comment] 2021-11-03 13:37
I think this is related to same issues as `gen2-triangulation` which isn't yet addressed unfortunately @RudyAramayo.

A potential fix is in the works, but we'll see whether it addresses the issue at hand as well.

Will keep you updated:)

**Comment by RudyAramayo** [comment] 2021-11-03 13:51
I have been through the librealsense pathway with some of the RealSense chips. I was not happy with the CPU load they used and want to encourage you guys because of the simplicity and offloaded processing that is being performed. So critical to start a project without pegging the CPU right off the bat.

**Comment by Luxonis-Brandon** [comment] 2021-11-03 18:37
Thanks @RudyAramayo !

**Comment by szabi-luxonis** [comment] 2021-11-07 17:28
@RudyAramayo  could you try installing the following library, it contains some fixes for Script node related memory allocation:
```
python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.11.1.1.dev+7498afce36f34dae5482c2bbf42db317e3e53dd5"
```

Then modifying the [script](https://github.com/luxonis/depthai-experiments/blob/master/gen2-face-recognition/main.py#L163) by adding the following (@alex-luxonis  [suggested](https://github.com/luxonis/depthai-python/issues/369#issuecomment-921814577) ):
`script.setProcessor(dai.ProcessorType.LEON_CSS)`

**Comment by RudyAramayo** [comment] 2021-11-13 17:38
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
depthai-sdk 1.1.2 requires depthai>2, but you have depthai 0.4.0.0+baacebe72eec4f257ddfc4d6cd45cb1725ecd6e4 which is incompatible.

**Comment by RudyAramayo** [comment] 2021-11-13 17:38
i think you guys have handled the issue, let me test and get back to you... the above error is from the initial bug report.

**Comment by RudyAramayo** [comment] 2021-11-13 17:43
i have understood where to add the code, will test now... i am new to the whole pipeline and what is going on ... very excited to learn something new this morning about how this script works... have not actually had time to read the scripts thuroughly yet.

**Comment by RudyAramayo** [comment] 2021-11-13 17:44
script = pipeline.create(dai.node.Script)
    script.setProcessor(dai.ProcessorType.LEON_CSS)

**Comment by RudyAramayo** [comment] 2021-11-13 17:51
ITS WORKING!!! i have 50% recognition that its me with weird angles and the crash no longer occurs. had to reinstall the python_requirements.py and this is the output after installation, I also modified the script and didn't check if that change was necessary for this particular crash:

Rodolfo@RIP depthai-main % python3 install_requirements.py
pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
WARNING: Skipping opencv-python as it is not installed.
WARNING: Skipping opencv-contrib-python as it is not installed.
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.3.1)
Found existing installation: depthai 2.11.1.1.dev0+7498afce36f34dae5482c2bbf42db317e3e53dd5
Uninstalling depthai-2.11.1.1.dev0+7498afce36f34dae5482c2bbf42db317e3e53dd5:
  Successfully uninstalled depthai-2.11.1.1.dev0+7498afce36f34dae5482c2bbf42db317e3e53dd5
Looking in indexes: https://pypi.org/simple, https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
Obtaining file:///Users/Rodolfo/Downloads/depthai-main/depthai_sdk (from -r requirements.txt (line 3))
  Preparing metadata (setup.py) ... done
Ignoring opencv-python: markers 'platform_machine == "armv6l" or platform_machine == "armv7l"' don't match your environment
Ignoring opencv-contrib-python: markers 'platform_machine == "armv6l" or platform_machine == "armv7l"' don't match your environment
Collecting requests==2.24.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting argcomplete==1.12.1
  Using cached argcomplete-1.12.1-py2.py3-none-any.whl (38 kB)
Collecting depthai==2.10.0.0.dev+7a0749a61597c086c5fd6e579618ae33accec8df
  Downloading https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/depthai-2.10.0.0.dev0%2B7a0749a61597c086c5fd6e579618ae33accec8df-cp39-cp39-macosx_10_9_x86_64.whl (10.2 MB)
     |████████████████████████████████| 10.2 MB 494 kB/s
Collecting opencv-python==4.5.1.48
  Downloading opencv_python-4.5.1.48-cp39-cp39-macosx_10_13_x86_64.whl (40.3 MB)
     |████████████████████████████████| 40.3 MB 331 kB/s
Collecting opencv-contrib-python==4.5.1.48
  Downloading opencv_contrib_python-4.5.1.48-cp39-cp39-macosx_10_13_x86_64.whl (51.3 MB)
     |████████████████████████████████| 51.3 MB 910 kB/s
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting numpy>=1.19.3
  Downloading numpy-1.21.4-cp39-cp39-macosx_10_9_x86_64.whl (17.0 MB)
     |████████████████████████████████| 17.0 MB 13.0 MB/s
Collecting blobconverter>=1.2.6
  Using cached blobconverter-1.2.6-py3-none-any.whl (10 kB)
Collecting pytube>=11.0.1
  Using cached pytube-11.0.1-py3-none-any.whl (56 kB)
Collecting PyYAML
  Downloading PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
     |████████████████████████████████| 197 kB 59.5 MB/s
Collecting boto3
  Downloading boto3-1.20.5-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 49.7 MB/s
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting botocore<1.24.0,>=1.23.5
  Downloading botocore-1.23.5-py3-none-any.whl (8.1 MB)
     |████████████████████████████████| 8.1 MB 63.1 MB/s
Collecting s3transfer<0.6.0,>=0.5.0
  Using cached s3transfer-0.5.0-py3-none-any.whl (79 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, urllib3, python-dateutil, jmespath, botocore, s3transfer, idna, chardet, certifi, requests, PyYAML, numpy, boto3, pytube, opencv-python, opencv-contrib-python, depthai, blobconverter, depthai-sdk, argcomplete
  WARNING: The script chardetect is installed in '/Users/Rodolfo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts f2py, f2py3 and f2py3.9 are installed in '/Users/Rodolfo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pytube is installed in '/Users/Rodolfo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script blobconverter is installed in '/Users/Rodolfo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for depthai-sdk
Successfully installed PyYAML-6.0 argcomplete-1.12.1 blobconverter-1.2.6 boto3-1.20.5 botocore-1.23.5 certifi-2021.10.8 chardet-3.0.4 depthai-2.10.0.0.dev0+7a0749a61597c086c5fd6e579618ae33accec8df depthai-sdk-1.1.2 idna-2.10 jmespath-0.10.0 numpy-1.21.4 opencv-contrib-python-4.5.1.48 opencv-python-4.5.1.48 python-dateutil-2.8.2 pytube-11.0.1 requests-2.24.0 s3transfer-0.5.0 six-1.16.0 urllib3-1.25.11
Ignoring open3d: markers 'platform_machine != "armv6l" and platform_machine != "armv7l" and python_version < "3.9"' don't match your environment
Collecting ffmpy3==0.2.4
  Using cached ffmpy3-0.2.4-py3-none-any.whl (6.0 kB)
Installing collected packages: ffmpy3
Successfully installed ffmpy3-0.2.4

**Closed** 2021-11-13 17:54 UTC

**Comment by RudyAramayo** [comment] 2021-11-13 17:59
85% recognition now....

**Comment by bhavers** [comment] 2022-02-06 17:28
I can confirm that it fails with ```RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'frame' (X_LINK_ERROR)'```

After downgrading the deptai library through installing the requirements it works ```python3 -m pip install -r requirements.txt```
